version: '3'
services:
  app:
    container_name: download-test
    restart: always
    build: .
    volumes:
      - /home/debian/test/server:/home/debian/test/server
      - /home/debian/test/file:/home/debian/test/file
    tty: true
    ports:
      - '4040:4040'