version: '3'
services:
  app:
    container_name: download-test
    restart: always
    build: .
    volumes:
      - /home/debian/test:/src/
      - /src/appRelated:/src/files
    tty: true
    ports:
      - '4040:4040'