version: '3'
services:
  app:
    container_name: download-test
    restart: always
    build: .
    volumes:
      - /home/debian/test:/home/debian/test
      - /src/appRelated:/home/debian/test/files
    tty: true
    ports:
      - '4040:4040'